language: node_js
node_js:
- "4.6.0"
cache:
  directories:
  - node_modules
sudo: false
script: npm run test_coverage
after_script:
- codeclimate-test-reporter < coverage/lcov.info
notifications:
  email: false
env:
  global:
  - NODE_ENV=test
